/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemperatureRouteImport } from './routes/temperature'
import { Route as PrecipitationRouteImport } from './routes/precipitation'
import { Route as HumidityRouteImport } from './routes/humidity'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMagdeburgRouteImport } from './routes/api/magdeburg'

const TemperatureRoute = TemperatureRouteImport.update({
  id: '/temperature',
  path: '/temperature',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecipitationRoute = PrecipitationRouteImport.update({
  id: '/precipitation',
  path: '/precipitation',
  getParentRoute: () => rootRouteImport,
} as any)
const HumidityRoute = HumidityRouteImport.update({
  id: '/humidity',
  path: '/humidity',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMagdeburgRoute = ApiMagdeburgRouteImport.update({
  id: '/api/magdeburg',
  path: '/api/magdeburg',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/humidity': typeof HumidityRoute
  '/precipitation': typeof PrecipitationRoute
  '/temperature': typeof TemperatureRoute
  '/api/magdeburg': typeof ApiMagdeburgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/humidity': typeof HumidityRoute
  '/precipitation': typeof PrecipitationRoute
  '/temperature': typeof TemperatureRoute
  '/api/magdeburg': typeof ApiMagdeburgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/humidity': typeof HumidityRoute
  '/precipitation': typeof PrecipitationRoute
  '/temperature': typeof TemperatureRoute
  '/api/magdeburg': typeof ApiMagdeburgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/humidity'
    | '/precipitation'
    | '/temperature'
    | '/api/magdeburg'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/humidity'
    | '/precipitation'
    | '/temperature'
    | '/api/magdeburg'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/humidity'
    | '/precipitation'
    | '/temperature'
    | '/api/magdeburg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  HumidityRoute: typeof HumidityRoute
  PrecipitationRoute: typeof PrecipitationRoute
  TemperatureRoute: typeof TemperatureRoute
  ApiMagdeburgRoute: typeof ApiMagdeburgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temperature': {
      id: '/temperature'
      path: '/temperature'
      fullPath: '/temperature'
      preLoaderRoute: typeof TemperatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precipitation': {
      id: '/precipitation'
      path: '/precipitation'
      fullPath: '/precipitation'
      preLoaderRoute: typeof PrecipitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/humidity': {
      id: '/humidity'
      path: '/humidity'
      fullPath: '/humidity'
      preLoaderRoute: typeof HumidityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/magdeburg': {
      id: '/api/magdeburg'
      path: '/api/magdeburg'
      fullPath: '/api/magdeburg'
      preLoaderRoute: typeof ApiMagdeburgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  HumidityRoute: HumidityRoute,
  PrecipitationRoute: PrecipitationRoute,
  TemperatureRoute: TemperatureRoute,
  ApiMagdeburgRoute: ApiMagdeburgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
